name: Update SHA256 Checksum After URL Commit

on:
  push:
    branches:
      - main
    paths:
      - 'Formula/devopstools.rb'

jobs:
  update-sha:
    if: github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

          SHA=$(git rev-parse HEAD)
          curl -L -o repo.tar.gz https://github.com/${GITHUB_REPOSITORY}/archive/${SHA}.tar.gz
          SHA256=$(sha256sum repo.tar.gz | awk '{ print $1 }')

          sed -i "s/sha256 \".*\"/sha256 \"${SHA256}\"/" Formula/devopstools.rb
          git add Formula/devopstools.rb
          git commit -m "CI: Update SHA256 checksum for ${SHA} [skip ci]" || echo "No changes"
          git push origin main