name: Update Homebrew Formula

on:
  push:
    tags:
      - 'v*'

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Extract Tag Name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download Release Tarball
        run: |
          curl -L -o release.tar.gz https://github.com/${{ github.repository }}/archive/refs/tags/${{ env.tag }}.tar.gz

      - name: Calculate SHA256 Checksum
        id: sha256
        run: |
          SHA256=$(sha256sum release.tar.gz | awk '{ print $1 }')
          echo "sha256=$SHA256" >> $GITHUB_ENV

      - name: Update Formula File
        run: |
          sed -i "s|url \".*\"|url \"https://github.com/${{ github.repository }}/archive/refs/tags/${{ env.tag }}.tar.gz\"|" Formula/devopstools.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ env.sha256 }}\"|" Formula/devopstools.rb
          sed -i "s|version \".*\"|version \"${{ env.tag }}\"|" Formula/devopstools.rb

      - name: Commit and Push Changes
        run: |
          git add Formula/devopstools.rb
          git commit -m "Update formula to version ${{ env.tag }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}