name: Update SHA256 Checksum

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-sha256:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Repo Tarball
        run: |
          curl -L -o repo.tar.gz https://github.com/${{ github.repository }}/archive/refs/heads/main.tar.gz
          sha256sum repo.tar.gz > sha256.txt

      - name: Extract SHA256
        id: sha
        run: |
          SHA=$(cut -d ' ' -f1 sha256.txt)
          echo "sha256=$SHA" >> $GITHUB_ENV
          echo "✅ SHA256 calculated: $SHA"

      - name: Update Formula
        run: |
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.sha256 }}\"/" Formula/devopstools.rb
          cat Formula/devopstools.rb

      - name: Configure Git for PAT Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Commit and Push Changes
        run: |
          git add Formula/devopstools.rb
          git commit -m "CI: Auto-update SHA256 checksum" || echo "No changes to commit."
          git push origin main --force
