name: Update SHA256 Checksum

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-sha256:
    if: github.actor != 'github-actions[bot]'  # prevent self-trigger on commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo (No Token Injection)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download Tarball and Calculate SHA256 (Commit-Specific)
        run: |
          echo "🔽 Downloading tarball for commit ${{ github.sha }}"
          curl -L -o repo.tar.gz https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz
          sha256sum repo.tar.gz > sha256.txt

      - name: Extract SHA256 Value
        id: sha
        run: |
          SHA=$(cut -d ' ' -f1 sha256.txt)
          echo "sha256=$SHA" >> $GITHUB_ENV
          echo "✅ Calculated SHA256: $SHA"

      - name: Update Formula File (Both URL and SHA256)
        run: |
          sed -i "s|url \".*\"|url \"https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz\"|" Formula/devopstools.rb
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.sha256 }}\"/" Formula/devopstools.rb
          echo "📝 Updated Formula file:"
          cat Formula/devopstools.rb

      - name: Configure Git for PAT Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}_
