name: Safe SHA256 and URL Update for Homebrew Formula

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-sha256:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (No Token Injection)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git for PAT Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Step 1: Update Formula URL (First Commit)
        env:
          CURRENT_SHA: ${{ github.sha }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "🔗 Updating the formula URL to commit SHA: $CURRENT_SHA"
          sed -i "s|url \".*\"|url \"https://github.com/${REPO_NAME}/archive/${CURRENT_SHA}.tar.gz\"|" Formula/devopstools.rb
          git add Formula/devopstools.rb
          git commit -m "CI: Update formula URL to $CURRENT_SHA [skip ci]" || echo "✅ No URL changes to commit."
          git push origin main

      - name: Step 2: Pull Latest Commit SHA (After URL Commit)
        id: get_sha
        run: |
          NEW_SHA=$(git rev-parse HEAD)
          echo "new_sha=$NEW_SHA" >> $GITHUB_ENV
          echo "✅ Latest SHA after URL commit: $NEW_SHA"

      - name: Step 3: Download Tarball and Calculate SHA256 (Correct Tarball)
        run: |
          echo "🔽 Downloading tarball for commit ${{ env.new_sha }}"
          curl -L -o repo.tar.gz https://github.com/${{ github.repository }}/archive/${{ env.new_sha }}.tar.gz
          sha256sum repo.tar.gz > sha256.txt
          SHA256_VALUE=$(cut -d ' ' -f1 sha256.txt)
          echo "sha256=$SHA256_VALUE" >> $GITHUB_ENV
          echo "✅ Calculated SHA256: $SHA256_VALUE"

      - name: Step 4: Update SHA256 in Formula and Commit Again
        run: |
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.sha256 }}\"/" Formula/devopstools.rb
          git add Formula/devopstools.rb
          git commit -m "CI: Update SHA256 checksum for ${{ env.new_sha }} [skip ci]" || echo "✅ No SHA256 changes to commit."
          git push origin main
