name: Update SHA256 Checksum

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-sha256:
    if: github.actor != 'github-actions[bot]'  # Prevent loop when bot commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Disable Token Injection)
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevent GITHUB_TOKEN overwriting git credentials

      - name: Download Tarball and Calculate SHA256
        run: |
          echo "🔽 Downloading tarball for commit ${{ github.sha }}"
          curl -L -o repo.tar.gz https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz
          sha256sum repo.tar.gz > sha256.txt

      - name: Extract SHA256 Value
        id: sha
        run: |
          SHA=$(cut -d ' ' -f1 sha256.txt)
          echo "sha256=$SHA" >> $GITHUB_ENV
          echo "✅ Calculated SHA256: $SHA"

      - name: Update Formula File (Replace URL and SHA256)
        run: |
          echo "📝 Updating Formula/devopstools.rb"
          sed -i "s|url \".*\"|url \"https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz\"|" Formula/devopstools.rb
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.sha256 }}\"/" Formula/devopstools.rb
          echo "✅ Formula file after update:"
          cat Formula/devopstools.rb

      - name: Configure Git for PAT Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          echo "✅ Git remote updated for PAT push."

      - name: Commit and Push Changes
        run: |
          git add Formula/devopstools.rb
          git commit -m "CI: Auto-update SHA256 checksum [skip ci]" || echo "✅ No changes to commit."
          git push origin main
