name: Update Formula URL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-url:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Update Formula URL
        run: |
          URL="https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.tar.gz"
          sed -i "s|url \".*\"|url \"${URL}\"|" Formula/devopstools.rb
          git add Formula/devopstools.rb
          git commit -m "CI: Update formula URL to ${GITHUB_SHA} [skip ci]" || echo "No changes"
          git push origin main
